services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: kukaNku
      MONGO_INITDB_ROOT_PASSWORD: janiK%4012
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=jani-secret
      - AUTH_SERVICE_URL=http://auth-service:8000
    depends_on:
      - auth-service
      - order-service
      - notification-service
      - cleaning-details-service
      - subscription-service
      - payment-service
      - user-management-service
      - review-media-service
      - support-service
  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET=jani-secret
      - GOOGLE_CLIENT_ID=23103692607-q7mn7md6ru5fk8bv6nq3fdnh3fsvohov.apps.googleusercontent.com
    env_file:
      - .env.docker
  order-service:
    build: ./order-service
    ports:
      - "8001:8001"
    environment:
      - JWT_SECRET=jani-secret
      - AUTH_SERVICE_URL=http://auth-service:8000
    env_file:
      - .env.docker
    depends_on:
      - mongodb
      - auth-service
  notification-service:
    build: ./notification-service
    ports:
      - "8002:8002"
    environment:
      - JWT_SECRET=jani-secret
      - AUTH_SERVICE_URL=http://auth-service:8000
    env_file:
      - .env
    depends_on:
      - mongodb
      - auth-service
  cleaning-details-service:
    build: ./cleaning-details-service
    ports:
      - "8003:8003"
    environment:
      - JWT_SECRET=jani-secret
      - AUTH_SERVICE_URL=http://auth-service:8000
    env_file:
      - .env.docker
    depends_on:
      - mongodb
      - auth-service
  subscription-service:
    build: ./subscription-service
    ports:
      - "8004:8004"
    environment:
      - JWT_SECRET=jani-secret
      - AUTH_SERVICE_URL=http://auth-service:8000
    env_file:
      - .env.docker
    depends_on:
      - mongodb
      - auth-service
  payment-service:
    build: ./payment-service
    ports:
      - "8005:8005"
    environment:
      - JWT_SECRET=jani-secret
      - AUTH_SERVICE_URL=http://auth-service:8000
      - ORDER_SERVICE_URL=http://order-service:8001
    env_file:
      - .env.docker
    depends_on:
      - mongodb
      - auth-service
  user-management-service:
    build: ./user-management-service
    ports:
      - "8006:8006"
    environment:
      - JWT_SECRET=jani-secret
      - AUTH_SERVICE_URL=http://auth-service:8000
    env_file:
      - .env.docker
    depends_on:
      - mongodb
      - auth-service
  review-media-service:
    build: ./review-media-service
    ports:
      - "8007:8007"
    environment:
      - JWT_SECRET=jani-secret
      - AUTH_SERVICE_URL=http://auth-service:8000
    env_file:
      - .env.docker
    depends_on:
      - mongodb
      - auth-service
  support-service:
    build: ./support-service
    ports:
      - "8008:8008"
    environment:
      - JWT_SECRET=jani-secret
      - AUTH_SERVICE_URL=http://auth-service:8000
      - NOTIFICATION_SERVICE_URL=http://notification-service:8002
      - USER_SERVICE_URL=http://user-management-service:8006

    env_file:
      - .env.docker
    depends_on:
      - mongodb
      - redis
      - auth-service
      - notification-service

volumes:
  mongodb_data:
  redis_data: