services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: kukaNku
      MONGO_INITDB_ROOT_PASSWORD: janiK%4012
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET=jani-secret
      - GOOGLE_CLIENT_ID=23103692607-q7mn7md6ru5fk8bv6nq3fdnh3fsvohov.apps.googleusercontent.com
    env_file:
      - .env
  order-service:
    build: ./order-service
    ports:
      - "8001:8001"
    environment:
      - JWT_SECRET=jani-secret
      - AUTH_SERVICE_URL=http://auth-service:8000
    env_file:
      - .env
    depends_on:
      - mongodb
      - auth-service
  cleaning-details-service:
    build: ./cleaning-details-service
    ports:
      - "8003:8003"
    environment:
      - JWT_SECRET=jani-secret
      - AUTH_SERVICE_URL=http://auth-service:8000
    env_file:
      - .env
    depends_on:
      - mongodb
      - auth-service
<<<<<<< HEAD

  subscription-service:
    build: ./subscription-service
    ports:
      - "8004:8004"
    environment:
      - JWT_SECRET=jani-secret
      - AUTH_SERVICE_URL=http://auth-service:8000
    env_file:
      - .env
    depends_on:
      - mongodb
      - auth-service

volumes:
  mongodb_data:
  redis_data:
#  cleaning-details-service:
#    build: ./cleaning-details-service
=======
#  notification-service:
#    build: ./notification-service
>>>>>>> ab0f246e9efcab4a63687f0256708a534dedcea0
#    ports:
#      - "8002:8002"
#    environment:
#      - JWT_SECRET=jani-secret
#      - AUTH_SERVICE_URL=http://auth-service:8000
#    env_file:
#      - .env
#    depends_on:
#      - mongodb
#      - auth-service
volumes:
  mongodb_data:
  redis_data:

